### ISSUE TITLE
Undefined method on cached objects

### ISSUE THREAD

**Issue by abhishek77in** [byroot/activerecord-typedstore#79] opened 2020-02-29 12:05 UTC
I have model called "Setting", I am trying to cache setting object in memory to prevent repeated database calls. But I am getting 

```
undefined method high? for #<Setting:0x00007fe7438534c8>
```
Here `high` is a boolean variable.

**Comment by byroot** [comment] 2020-03-02 10:19
Your issue isn't actionable because you don't give any relevant information that would allow me to answer you.

Closing for now, I'll re-open if you provide a reproduction script, or at least a code snippet, backtrace etc.

**Closed by byroot** 2020-03-02 10:19 UTC

**Comment by abhishek77in** [comment] 2020-03-02 10:23
You are right. Sorry about that. Will post more details.
